### ISSUE TITLE
Ubuntu: builds fail complaining about `strlcpy`, but it's not what you think

### ISSUE THREAD

**Issue by vielmetti** [jpmens/msoak#9] opened 2020-01-04 21:54 UTC
I tried to build on Ubuntu 16.04, after fixing the `libmosquitto` issue in #8. It complained about `strlcpy` missing. Looking at that it was clear that I needed libbsd, so I checked to see that it was installed (it was).

Look at the Makefile, discover that the default Makefile is set up for MacOS builds, and that I need to edit it just a bit to build on Linux, which I did, and all is OK.

**Comment by jpmens** [comment] 2020-01-04 21:57
That’s correct: the `Makefile` needs editing (commenting, removing comments) for the desired platform. I am hoping somebody comes forward to volunteer to create packages for Linux systems (I’m working on FreeBSD/OpenBSD) which will likely solve that.

Closing as not a bug, unless you think it should be clarified in the `README.md` in which case please complain!

**Comment by vielmetti** [comment] 2020-01-04 22:02
Definitely "not a bug", but I'll see if there's a simple edit to the README that can clarify that tweaking the Makefile is a prerequsite to building.

**Comment by jpmens** [comment] 2020-01-04 22:05
Back in the old days (remember those?) we had Makefiles which asked along the lines of `”what do you want to make? Specify linux,solaris,sunos,hpux, etc”`. Would that be something you think we should add to the `Makefile`?

**Comment by vielmetti** [comment] 2020-01-04 22:08
I do remember the old days! And I don't want to go down the whole miserable `autoconfig` route, but it would be really pleasant for a lot of reasons if a single portable Makefile successfully built on all relevant systems.

**Comment by jpmens** [comment] 2020-01-04 22:13
No autoconfig, no cmake, and I don’t want to enforce Gnu make to the *BSD world (even though there are many packages which do, but these simple utilities shouldn’t require that IMO).

**Comment by jpmens** [comment] 2020-01-04 22:20
What does this `Makefile` print on your systems? (It correctly detects `darwin`, `freebsd`, and `openbsd`, i.e. it works with Gnu make and BSD make.)

```Makefile
OS.exec = uname -s | tr '[A-Z]' '[a-z]'
OS = $(shell $(OS.exec))$(OS.exec:sh)
show:
        @echo $(OS)
```

/[via](https://news.ycombinator.com/item?id=15066541)

**Comment by vielmetti** [comment] 2020-01-04 22:27
I get `linux` on the Ubuntu 16 and the Ubuntu 18 WSL system, which is correct. 
The WSL system has GNU Make 4.1, and the Ubuntu 16 system also has GNU Make 4.1.

Looks good at least for a first pass!

**Comment by jpmens** [comment] 2020-01-05 10:21
Closing and opening enhancement in #13

**Closed as completed by jpmens** 2020-01-05 10:21 UTC
